version: "3.9"

services:

  web:
    build:
      context: .
      target: base
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./ams-proj:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  db:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  celery:
    build:
      context: .
      target: base
    command: celery -A umsproj worker -l info
    volumes:
      - ./ams-proj:/app
    env_file:
      - .env
    depends_on:
      - db
      - redis

  celery-beat:
    build:
      context: .
      target: base
    command: celery -A umsproj beat -l info
    volumes:
      - ./ams-proj:/app
    env_file:
      - .env
    depends_on:
      - db
      - redis

volumes:
  postgres_data: