# Generated by Django 5.2.7 on 2025-10-15 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='program',
            field=models.CharField(default='BSC Computer Science', max_length=50),
            preserve_default=False,
        ),
    ]
