# Generated by Django 5.2.7 on 2025-11-05 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umsapp', '0002_student_program'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
                ('added_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='added_to_sessions', to='umsapp.student')),
                ('adder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='added_students', to='umsapp.student')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_attendance', to='umsapp.session')),
            ],
            options={
                'unique_together': {('session', 'adder', 'added_student')},
            },
        ),
    ]
