# Generated by Django 5.2.7 on 2025-11-08 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umsapp', '0002_remove_customuser_can_logout'),
    ]

    operations = [
        
    ]
