# Generated by Django 5.2.7 on 2025-11-06 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umsapp', '0003_pendingattendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('Fall', 'Fall'), ('Spring', 'Spring'), ('Summer', 'Summer')], max_length=10)),
                ('year', models.IntegerField()),
                ('status', models.CharField(choices=[('Past', 'Past'), ('Current', 'Current')], max_length=10)),
            ],
            options={
                'unique_together': {('period', 'year')},
            },
        ),
    ]
