# Generated by Django 5.2.7 on 2025-11-08 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('umsapp', '0001_initial'),
    ]

    operations = [
        
    ]
