# Generated by Django 5.2.7 on 2025-11-12 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umsapp', '0003_customuser_can_logout'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='semester',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='umsapp.semester'),
            preserve_default=False,
        ),
    ]
