# Generated by Django 5.2.7 on 2026-07-05 13:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField(unique=True)),
                ('ip_address', models.CharField(blank=True, max_length=10)),
                ('platform', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_token', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('type', models.CharField(choices=[('MARKED_ABSENT', 'Marked Absent'), ('MARKED_PRESENT', 'Marked Present'), ('MARKED_PENDING', 'Marked Pending'), ('ATTENDANCE_JUSTIFIED', 'Attendance Justified'), ('SESSION_STARTED', 'Session Started'), ('SESSION_ENDED', 'Session Ended'), ('COURSE_CREATED', 'Course Created'), ('COURSE_UPDATED', 'Course Updated'), ('COURSE_DELETED', 'Course Deleted'), ('COURSE_OFFERING_CREATED', 'Course Offering Created'), ('COURSE_OFFERING_UPDATED', 'Course Offering Updated'), ('COURSE_OFFERING_DELETED', 'Course Offering Deleted'), ('ENROLLMENT_CREATED', 'Enrolled in Course'), ('ENROLLMENT_DELETED', 'Removed from Course'), ('ASSIGNMENT_CREATED', 'Assigned to Course'), ('ASSIGNMENT_DELETED', 'Removed from Course Assignment'), ('REGISTERED', 'Registered Successfully'), ('PASSWORD_RESET', 'Password Reset'), ('PASSWORD_CHANGED', 'Password Changed'), ('GENERAL', 'General'), ('ANNOUNCEMENT', 'Announcement'), ('REMINDER', 'Reminder')], default='GENERAL', max_length=50)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
