# Generated by Django 5.2.7 on 2026-07-01 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0001_initial'),
        ('auth_app', '0001_initial'),
        ('class_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class_sessions.session'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth_app.student'),
        ),
        migrations.AddField(
            model_name='pendingattendance',
            name='added_student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_attendances', to='auth_app.student'),
        ),
        migrations.AddField(
            model_name='pendingattendance',
            name='adder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='added_attendances', to='auth_app.student'),
        ),
        migrations.AddField(
            model_name='pendingattendance',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_attendances', to='class_sessions.session'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'session')},
        ),
        migrations.AlterUniqueTogether(
            name='pendingattendance',
            unique_together={('session', 'added_student')},
        ),
    ]
