# Generated by Django 5.2.7 on 2026-07-05 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_initial'),
        ('auth_app', '0002_customuser_must_change_password_passwordresetotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingattendance',
            name='added_student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pending_attendances', to='auth_app.student'),
        ),
        migrations.AlterField(
            model_name='pendingattendance',
            name='adder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='added_attendances', to='auth_app.student'),
        ),
    ]
