# Generated by Django 5.2.7 on 2026-03-13 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umsapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseoffering',
            name='id',
        ),
        migrations.AlterField(
            model_name='courseoffering',
            name='course_offering_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
