# Generated by Django 5.2.7 on 2026-03-14 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umsapp', '0003_courseassignment_session_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('added_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_attendances', to='umsapp.student')),
                ('adder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='added_attendances', to='umsapp.student')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_attendances', to='umsapp.session')),
            ],
            options={
                'unique_together': {('session', 'added_student')},
            },
        ),
    ]
