# Generated by Django 5.2.7 on 2026-04-11 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umsapp', '0004_pendingattendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseoffering',
            name='course_offering_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
